const $ = (s) => document.querySelector(s);
const screens = document.querySelectorAll('.screen');
const canvas = $('#game-canvas'), ctx = canvas.getContext('2d');
const data = JSON.parse(localStorage.getItem('templeRush') || '{"coins":120,"best":0,"items":{"shield":0,"magnet":0,"boost":0}}');
const shopItems = [{id:'shield',icon:'🛡️',name:'神圣护盾',desc:'抵挡一次障碍撞击',price:35},{id:'magnet',icon:'🧲',name:'金币磁铁',desc:'8 秒内自动吸附金币',price:25},{id:'boost',icon:'⚡',name:'疾行符文',desc:'瞬间获得 300 米距离',price:45}];
let game, raf, touchX;
function save(){localStorage.setItem('templeRush',JSON.stringify(data)); updateStats()}
function updateStats(){ $('#coin-count').textContent=data.coins;$('#shop-coins').textContent=data.coins;$('#best-score').textContent=data.best }
function show(name){cancelAnimationFrame(raf);screens.forEach(s=>s.classList.toggle('active',s.id===name)); if(name==='shop') renderShop(); updateStats()}
function renderShop(){ $('#shop-grid').innerHTML=shopItems.map(x=>`<article class="shop-item"><div class="item-icon">${x.icon}</div><div><h3>${x.name}</h3><p>${x.desc}</p></div><button class="buy" data-buy="${x.id}">🪙 ${x.price}</button></article>`).join('') }
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){const x=a.dataset.action;if(x==='start') start();else if(x==='pause') pause();else if(x==='resume') resume();else if(x==='reset'){if(confirm('确定重置所有金币和道具吗？')){data.coins=120;data.best=0;data.items={shield:0,magnet:0,boost:0};save();show('home')}}else show(x)} const buy=e.target.closest('[data-buy]');if(buy){const item=shopItems.find(i=>i.id===buy.dataset.buy);if(data.coins>=item.price){data.coins-=item.price;data.items[item.id]++;save();buy.textContent='已拥有 '+data.items[item.id];buy.classList.add('owned')}else alert('金币不足，先去冒险吧！')} const sw=e.target.closest('[data-setting]');if(sw)sw.classList.toggle('on')});
function start(){show('game'); $('#pause-overlay').classList.add('hidden');$('#result-overlay').classList.add('hidden');game={lane:1,dist:0,coins:0,start:performance.now(),last:performance.now(),objects:[],shield:false,magnetUntil:0,paused:false};renderItems();raf=requestAnimationFrame(loop)}
function renderItems(){ $('#item-bar').innerHTML=shopItems.map(i=>`<button class="item-use" data-item="${i.id}" ${data.items[i.id]?'':'disabled'}>${i.icon}<small>${data.items[i.id]}</small></button>`).join('');document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>useItem(b.dataset.item)) }
function useItem(id){if(!game||!data.items[id])return;data.items[id]--;if(id==='shield')game.shield=true;if(id==='magnet')game.magnetUntil=performance.now()+8000;if(id==='boost')game.dist+=300;save();renderItems()}
function move(dir){if(game&&!game.paused)game.lane=Math.max(0,Math.min(2,game.lane+dir))} window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.key===' ')useItem('shield')});canvas.addEventListener('touchstart',e=>touchX=e.touches[0].clientX);canvas.addEventListener('touchend',e=>{if(touchX){let d=e.changedTouches[0].clientX-touchX;if(Math.abs(d)>25)move(d>0?1:-1);touchX=null}});
function pause(){if(!game)return;game.paused=true;$('#pause-overlay').classList.remove('hidden');cancelAnimationFrame(raf)}function resume(){game.paused=false;game.last=performance.now();$('#pause-overlay').classList.add('hidden');raf=requestAnimationFrame(loop)}
function loop(now){if(!game||game.paused||game.over)return;const dt=Math.min((now-game.last)/1000,.05);game.last=now;const speed=Math.min(9,3+game.dist/220);game.dist+=speed*dt*10;if(Math.random()<dt*(.85+speed/9))game.objects.push({lane:Math.floor(Math.random()*3),y:-45,type:Math.random()<.62?'rock':'coin'});for(const o of game.objects)o.y+=speed*dt*68;game.objects=game.objects.filter(o=>{if(o.y>680&&o.y<770&&o.lane===game.lane){if(o.type==='coin'){game.coins++;return false}if(game.shield){game.shield=false;return false}end();return false}if(o.type==='coin'&&game.magnetUntil>now&&o.y>460){game.coins++;return false}return o.y<850});if(game.over)return;draw(speed,now);$('#distance').textContent=Math.floor(game.dist);$('#run-coins').textContent=game.coins;raf=requestAnimationFrame(loop)}
function roadX(lane,y){const depth=Math.max(0,Math.min(1,(y-90)/670));return 240+(lane-1)*(18+depth*102)}
function draw(speed,now){
  const w=canvas.width,h=canvas.height,phase=now/1000*speed*2.7;
  ctx.clearRect(0,0,w,h);
  const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#b7cec0');sky.addColorStop(.18,'#789c86');sky.addColorStop(.5,'#31594e');sky.addColorStop(1,'#132b2b');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);
  // Atmospheric layers, wet stone and a distant gateway give the runner a less graphic, more cinematic jungle environment.
  ctx.globalAlpha=.28;ctx.fillStyle='#d5ddbd';for(let i=0;i<6;i++){ctx.beginPath();ctx.ellipse(55+i*82,130+Math.sin(i)*10,95,23,0,0,7);ctx.fill()}ctx.globalAlpha=1;
  ctx.fillStyle='#365f4d';ctx.beginPath();ctx.moveTo(0,145);ctx.lineTo(92,74);ctx.lineTo(167,144);ctx.lineTo(250,61);ctx.lineTo(352,146);ctx.lineTo(439,83);ctx.lineTo(w,145);ctx.lineTo(w,220);ctx.lineTo(0,220);ctx.fill();ctx.fillStyle='#1d493d';ctx.beginPath();ctx.moveTo(0,160);ctx.lineTo(105,100);ctx.lineTo(185,165);ctx.lineTo(300,112);ctx.lineTo(w,161);ctx.lineTo(w,232);ctx.lineTo(0,232);ctx.fill();
  ctx.fillStyle='#244d3d';for(let x=-20;x<w+35;x+=23){const tree=45+Math.abs(Math.sin(x*12))*38;ctx.beginPath();ctx.moveTo(x-22,180);ctx.quadraticCurveTo(x,180-tree,x+22,180);ctx.quadraticCurveTo(x,137,x-22,180);ctx.fill()}
  ctx.fillStyle='#6f755b';ctx.fillRect(200,72,80,73);ctx.fillStyle='#899076';ctx.fillRect(205,76,70,6);ctx.fillStyle='#222f2a';ctx.beginPath();ctx.arc(240,111,22,Math.PI,0);ctx.lineTo(262,145);ctx.lineTo(218,145);ctx.fill();ctx.fillStyle='#59604f';ctx.fillRect(191,135,98,12);
  const road=ctx.createLinearGradient(0,100,0,h);road.addColorStop(0,'#687362');road.addColorStop(1,'#263b39');ctx.fillStyle=road;ctx.beginPath();ctx.moveTo(202,140);ctx.lineTo(278,140);ctx.lineTo(475,h);ctx.lineTo(5,h);ctx.fill();
  for(let i=0;i<18;i++){const t=((i/18)+(phase%1)/18)%1,y=140+Math.pow(t,1.72)*660,half=38+Math.pow(t,1.72)*200;ctx.strokeStyle=i%2?'#7d826a':'#4b5b51';ctx.globalAlpha=.7;ctx.lineWidth=1+9*t;ctx.beginPath();ctx.moveTo(240-half,y);ctx.lineTo(240+half,y);ctx.stroke();ctx.globalAlpha=1}
  for(let i=-2;i<=2;i++){ctx.strokeStyle='#293c38';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(240+i*12,142);ctx.lineTo(240+i*96,h);ctx.stroke()}
  for(const side of [-1,1]){ctx.fillStyle='#153a32';ctx.beginPath();ctx.moveTo(240+side*50,145);ctx.lineTo(240+side*245,h);ctx.lineTo(240+side*180,h);ctx.fill();for(let y=205;y<h;y+=180){const x=240+side*(55+(y-140)*.31),s=.5+(y/h);ctx.fillStyle='#5e6954';ctx.fillRect(x-10*s,y-60*s,20*s,74*s);ctx.fillStyle='#788067';ctx.fillRect(x-7*s,y-58*s,5*s,68*s);ctx.fillStyle='#173c31';for(let leaf=0;leaf<5;leaf++){ctx.beginPath();ctx.ellipse(x+side*(12+leaf*8)*s,y-60*s-leaf*9*s,22*s,8*s,side*.8,0,7);ctx.fill()}}}
  game.objects.forEach(o=>{const depth=Math.max(0,(o.y-40)/740),x=roadX(o.lane,o.y),scale=.28+depth*.95;if(o.type==='coin'){ctx.fillStyle='#6b4b21';ctx.beginPath();ctx.ellipse(x+3,o.y+5,13*scale,5*scale,0,0,7);ctx.fill();ctx.fillStyle='#ffd25e';ctx.beginPath();ctx.arc(x,o.y,17*scale,0,7);ctx.fill();ctx.strokeStyle='#fff0a2';ctx.lineWidth=2*scale;ctx.stroke();ctx.fillStyle='#a96d24';ctx.font=`${16*scale}px sans-serif`;ctx.fillText('◈',x-7*scale,o.y+5*scale)}else{ctx.fillStyle='#4c5148';ctx.beginPath();ctx.moveTo(x,o.y-27*scale);ctx.lineTo(x+25*scale,o.y+22*scale);ctx.lineTo(x-25*scale,o.y+22*scale);ctx.closePath();ctx.fill();ctx.strokeStyle='#9c9a77';ctx.lineWidth=2*scale;ctx.stroke()}});
  const px=roadX(game.lane,710),run=Math.sin(phase*2.4),bob=Math.abs(run)*6,py=685+bob;
  ctx.fillStyle='#0c2829aa';ctx.beginPath();ctx.ellipse(px,755,41,10,0,0,7);ctx.fill();
  // Runner viewed from behind: alternating limbs and body bob create a clear forward-running cadence.
  ctx.strokeStyle='#1b2224';ctx.lineWidth=15;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(px-9,py+49);ctx.lineTo(px-18-run*19,py+82);ctx.moveTo(px+9,py+49);ctx.lineTo(px+18+run*19,py+82);ctx.stroke();ctx.strokeStyle='#8e9c8e';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(px-18-run*19,py+82);ctx.lineTo(px-30-run*20,py+83);ctx.moveTo(px+18+run*19,py+82);ctx.lineTo(px+30+run*20,py+83);ctx.stroke();
  ctx.strokeStyle='#c88c5b';ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(px-18,py+16);ctx.lineTo(px-37+run*18,py+40);ctx.moveTo(px+18,py+16);ctx.lineTo(px+37-run*18,py+40);ctx.stroke();
  const shirt=ctx.createLinearGradient(px-24,py,px+24,py+58);shirt.addColorStop(0,'#875040');shirt.addColorStop(.5,'#b86143');shirt.addColorStop(1,'#4d3431');ctx.fillStyle=shirt;ctx.beginPath();ctx.moveTo(px-23,py+2);ctx.lineTo(px+23,py+2);ctx.lineTo(px+17,py+57);ctx.lineTo(px-17,py+57);ctx.closePath();ctx.fill();ctx.strokeStyle='#d9895d';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(px,py+6);ctx.lineTo(px,py+52);ctx.stroke();ctx.fillStyle='#d99b68';ctx.beginPath();ctx.arc(px,py-15,18,0,7);ctx.fill();ctx.fillStyle='#2d2927';ctx.beginPath();ctx.arc(px,py-21,19,Math.PI,0);ctx.lineTo(px+17,py-12);ctx.lineTo(px-17,py-12);ctx.fill();
  if(game.shield){ctx.strokeStyle='#9cffdc';ctx.lineWidth=4;ctx.beginPath();ctx.arc(px,py+20,58,0,7);ctx.stroke()}if(game.magnetUntil>now){ctx.strokeStyle='#f7ca63';ctx.lineWidth=3;ctx.beginPath();ctx.arc(px,py+20,70+Math.sin(phase*4)*6,0,7);ctx.stroke()}
  ctx.fillStyle='#fff';ctx.font='12px sans-serif';ctx.fillText('速度 '+speed.toFixed(1)+'/ 9.0',18,95);
}
function end(){game.over=true;cancelAnimationFrame(raf);data.coins+=game.coins;data.best=Math.max(data.best,Math.floor(game.dist));save();$('#final-distance').textContent=Math.floor(game.dist);$('#final-coins').textContent=game.coins;$('#result-overlay').classList.remove('hidden')}
updateStats();
