const $ = (s) => document.querySelector(s);
const screens = document.querySelectorAll('.screen');
const canvas = $('#game-canvas'), ctx = canvas.getContext('2d');
const data = JSON.parse(localStorage.getItem('templeRush') || '{"coins":120,"best":0,"items":{"shield":0,"magnet":0,"boost":0}}');
const shopItems = [{id:'shield',icon:'🛡️',name:'神圣护盾',desc:'抵挡一次障碍撞击',price:35},{id:'magnet',icon:'🧲',name:'金币磁铁',desc:'8 秒内自动吸附金币',price:25},{id:'boost',icon:'⚡',name:'疾行符文',desc:'瞬间获得 300 米距离',price:45}];
let game, raf, touchX;
function save(){localStorage.setItem('templeRush',JSON.stringify(data)); updateStats()}
function updateStats(){ $('#coin-count').textContent=data.coins;$('#shop-coins').textContent=data.coins;$('#best-score').textContent=data.best }
function show(name){cancelAnimationFrame(raf);screens.forEach(s=>s.classList.toggle('active',s.id===name)); if(name==='shop') renderShop(); updateStats()}
function renderShop(){ $('#shop-grid').innerHTML=shopItems.map(x=>`<article class="shop-item"><div class="item-icon">${x.icon}</div><div><h3>${x.name}</h3><p>${x.desc}</p></div><button class="buy" data-buy="${x.id}">🪙 ${x.price}</button></article>`).join('') }
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){const x=a.dataset.action;if(x==='start') start();else if(x==='pause') pause();else if(x==='resume') resume();else if(x==='reset'){if(confirm('确定重置所有金币和道具吗？')){data.coins=120;data.best=0;data.items={shield:0,magnet:0,boost:0};save();show('home')}}else show(x)} const buy=e.target.closest('[data-buy]');if(buy){const item=shopItems.find(i=>i.id===buy.dataset.buy);if(data.coins>=item.price){data.coins-=item.price;data.items[item.id]++;save();buy.textContent='已拥有 '+data.items[item.id];buy.classList.add('owned')}else alert('金币不足，先去冒险吧！')} const sw=e.target.closest('[data-setting]');if(sw)sw.classList.toggle('on')});
function start(){show('game'); $('#pause-overlay').classList.add('hidden');$('#result-overlay').classList.add('hidden');game={lane:1,dist:0,coins:0,start:performance.now(),last:performance.now(),objects:[],shield:false,magnetUntil:0,paused:false};renderItems();raf=requestAnimationFrame(loop)}
function renderItems(){ $('#item-bar').innerHTML=shopItems.map(i=>`<button class="item-use" data-item="${i.id}" ${data.items[i.id]?'':'disabled'}>${i.icon}<small>${data.items[i.id]}</small></button>`).join('');document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>useItem(b.dataset.item)) }
function useItem(id){if(!game||!data.items[id])return;data.items[id]--;if(id==='shield')game.shield=true;if(id==='magnet')game.magnetUntil=performance.now()+8000;if(id==='boost')game.dist+=300;save();renderItems()}
function move(dir){if(game&&!game.paused)game.lane=Math.max(0,Math.min(2,game.lane+dir))} window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.key===' ')useItem('shield')});canvas.addEventListener('touchstart',e=>touchX=e.touches[0].clientX);canvas.addEventListener('touchend',e=>{if(touchX){let d=e.changedTouches[0].clientX-touchX;if(Math.abs(d)>25)move(d>0?1:-1);touchX=null}});
function pause(){if(!game)return;game.paused=true;$('#pause-overlay').classList.remove('hidden');cancelAnimationFrame(raf)}function resume(){game.paused=false;game.last=performance.now();$('#pause-overlay').classList.add('hidden');raf=requestAnimationFrame(loop)}
function loop(now){if(!game||game.paused||game.over)return;const dt=Math.min((now-game.last)/1000,.05);game.last=now;const speed=Math.min(9,3+game.dist/220);game.dist+=speed*dt*10;if(Math.random()<dt*(.85+speed/9))game.objects.push({lane:Math.floor(Math.random()*3),y:-45,type:Math.random()<.62?'rock':'coin'});for(const o of game.objects)o.y+=speed*dt*68;game.objects=game.objects.filter(o=>{if(o.y>680&&o.y<770&&o.lane===game.lane){if(o.type==='coin'){game.coins++;return false}if(game.shield){game.shield=false;return false}end();return false}if(o.type==='coin'&&game.magnetUntil>now&&o.y>460){game.coins++;return false}return o.y<850});if(game.over)return;draw(speed,now);$('#distance').textContent=Math.floor(game.dist);$('#run-coins').textContent=game.coins;raf=requestAnimationFrame(loop)}
function draw(speed,now){const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#5a8655');grad.addColorStop(.34,'#285749');grad.addColorStop(1,'#172c30');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.fillStyle='#152c2d';ctx.beginPath();ctx.moveTo(165,0);ctx.lineTo(315,0);ctx.lineTo(470,h);ctx.lineTo(10,h);ctx.fill();for(let y=40;y<h;y+=65){ctx.strokeStyle='#e2bd5f55';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(240,y);ctx.lineTo(240,y+35);ctx.stroke()}game.objects.forEach(o=>{const x=145+o.lane*95,y=o.y;if(o.type==='coin'){ctx.fillStyle='#f6bd58';ctx.beginPath();ctx.arc(x,y,15,0,7);ctx.fill();ctx.fillStyle='#9e6927';ctx.font='17px sans-serif';ctx.fillText('◈',x-8,y+6)}else{ctx.fillStyle='#8b7761';ctx.beginPath();ctx.moveTo(x,y-22);ctx.lineTo(x+20,y+20);ctx.lineTo(x-20,y+20);ctx.fill()}});const px=145+game.lane*95,py=710;ctx.fillStyle=game.shield?'#80dec7':'#f3c66d';ctx.beginPath();ctx.arc(px,py,23,0,7);ctx.fill();ctx.fillStyle='#253642';ctx.fillRect(px-17,py+19,34,35);if(game.shield){ctx.strokeStyle='#c9fff1';ctx.lineWidth=4;ctx.beginPath();ctx.arc(px,py+10,42,0,7);ctx.stroke()}ctx.fillStyle='#fff';ctx.font='12px sans-serif';ctx.fillText('速度 '+speed.toFixed(1)+'/ 9.0',18,95)}
function end(){game.over=true;cancelAnimationFrame(raf);data.coins+=game.coins;data.best=Math.max(data.best,Math.floor(game.dist));save();$('#final-distance').textContent=Math.floor(game.dist);$('#final-coins').textContent=game.coins;$('#result-overlay').classList.remove('hidden')}
updateStats();
