const $ = (s) => document.querySelector(s);
const screens = document.querySelectorAll('.screen');
const canvas = $('#game-canvas'), ctx = canvas.getContext('2d');
const data = JSON.parse(localStorage.getItem('templeRush') || '{"coins":120,"best":0,"items":{"shield":0,"magnet":0,"boost":0}}');
const shopItems = [{id:'shield',icon:'🛡️',name:'神圣护盾',desc:'抵挡一次障碍撞击',price:35},{id:'magnet',icon:'🧲',name:'金币磁铁',desc:'8 秒内自动吸附金币',price:25},{id:'boost',icon:'⚡',name:'疾行符文',desc:'瞬间获得 300 米距离',price:45}];
let game, raf, touchX;
function save(){localStorage.setItem('templeRush',JSON.stringify(data)); updateStats()}
function updateStats(){ $('#coin-count').textContent=data.coins;$('#shop-coins').textContent=data.coins;$('#best-score').textContent=data.best }
function show(name){cancelAnimationFrame(raf);screens.forEach(s=>s.classList.toggle('active',s.id===name)); if(name==='shop') renderShop(); updateStats()}
function renderShop(){ $('#shop-grid').innerHTML=shopItems.map(x=>`<article class="shop-item"><div class="item-icon">${x.icon}</div><div><h3>${x.name}</h3><p>${x.desc}</p></div><button class="buy" data-buy="${x.id}">🪙 ${x.price}</button></article>`).join('') }
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){const x=a.dataset.action;if(x==='start') start();else if(x==='pause') pause();else if(x==='resume') resume();else if(x==='reset'){if(confirm('确定重置所有金币和道具吗？')){data.coins=120;data.best=0;data.items={shield:0,magnet:0,boost:0};save();show('home')}}else show(x)} const buy=e.target.closest('[data-buy]');if(buy){const item=shopItems.find(i=>i.id===buy.dataset.buy);if(data.coins>=item.price){data.coins-=item.price;data.items[item.id]++;save();buy.textContent='已拥有 '+data.items[item.id];buy.classList.add('owned')}else alert('金币不足，先去冒险吧！')} const sw=e.target.closest('[data-setting]');if(sw)sw.classList.toggle('on')});
function start(){show('game'); $('#pause-overlay').classList.add('hidden');$('#result-overlay').classList.add('hidden');game={lane:1,dist:0,coins:0,start:performance.now(),last:performance.now(),objects:[],shield:false,magnetUntil:0,paused:false};renderItems();raf=requestAnimationFrame(loop)}
function renderItems(){ $('#item-bar').innerHTML=shopItems.map(i=>`<button class="item-use" data-item="${i.id}" ${data.items[i.id]?'':'disabled'}>${i.icon}<small>${data.items[i.id]}</small></button>`).join('');document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>useItem(b.dataset.item)) }
function useItem(id){if(!game||!data.items[id])return;data.items[id]--;if(id==='shield')game.shield=true;if(id==='magnet')game.magnetUntil=performance.now()+8000;if(id==='boost')game.dist+=300;save();renderItems()}
function move(dir){if(game&&!game.paused)game.lane=Math.max(0,Math.min(2,game.lane+dir))} window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.key===' ')useItem('shield')});canvas.addEventListener('touchstart',e=>touchX=e.touches[0].clientX);canvas.addEventListener('touchend',e=>{if(touchX){let d=e.changedTouches[0].clientX-touchX;if(Math.abs(d)>25)move(d>0?1:-1);touchX=null}});
function pause(){if(!game)return;game.paused=true;$('#pause-overlay').classList.remove('hidden');cancelAnimationFrame(raf)}function resume(){game.paused=false;game.last=performance.now();$('#pause-overlay').classList.add('hidden');raf=requestAnimationFrame(loop)}
function loop(now){if(!game||game.paused||game.over)return;const dt=Math.min((now-game.last)/1000,.05);game.last=now;const speed=Math.min(9,3+game.dist/220);game.dist+=speed*dt*10;if(Math.random()<dt*(.85+speed/9))game.objects.push({lane:Math.floor(Math.random()*3),y:-45,type:Math.random()<.62?'rock':'coin'});for(const o of game.objects)o.y+=speed*dt*68;game.objects=game.objects.filter(o=>{if(o.y>680&&o.y<770&&o.lane===game.lane){if(o.type==='coin'){game.coins++;return false}if(game.shield){game.shield=false;return false}end();return false}if(o.type==='coin'&&game.magnetUntil>now&&o.y>460){game.coins++;return false}return o.y<850});if(game.over)return;draw(speed,now);$('#distance').textContent=Math.floor(game.dist);$('#run-coins').textContent=game.coins;raf=requestAnimationFrame(loop)}
function roadX(lane,y){const depth=Math.max(0,Math.min(1,(y-90)/670));return 240+(lane-1)*(18+depth*102)}
function draw(speed,now){
  const w=canvas.width,h=canvas.height,phase=now/1000*speed*2.7;
  ctx.clearRect(0,0,w,h);
  const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#b2d6b2');sky.addColorStop(.22,'#5d9871');sky.addColorStop(1,'#183b35');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);
  // Distant temple and jungle establish a destination; repeated ground bands make the camera feel like it is moving forward.
  ctx.fillStyle='#2d5d43';for(let x=-40;x<w+40;x+=46){const tree=55+Math.sin(x*7)*22;ctx.beginPath();ctx.arc(x,135,tree,0,7);ctx.fill()}ctx.fillStyle='#415c3b';ctx.fillRect(205,55,70,65);ctx.fillStyle='#d5bb73';ctx.fillRect(218,75,44,45);ctx.fillStyle='#254837';ctx.beginPath();ctx.arc(240,99,14,0,7);ctx.fill();
  ctx.fillStyle='#253f38';ctx.beginPath();ctx.moveTo(205,90);ctx.lineTo(275,90);ctx.lineTo(480,h);ctx.lineTo(0,h);ctx.fill();
  for(let i=0;i<17;i++){const t=((i/17)+(phase%1)/17)%1,y=90+Math.pow(t,1.75)*710,half=35+Math.pow(t,1.75)*225;ctx.strokeStyle=i%2?'#55715b':'#466450';ctx.lineWidth=2+12*t;ctx.beginPath();ctx.moveTo(240-half,y);ctx.lineTo(240+half,y);ctx.stroke()}
  for(const side of [-1,1]){ctx.fillStyle='#183a33';ctx.beginPath();ctx.moveTo(240+side*65,95);ctx.lineTo(240+side*235,h);ctx.lineTo(240+side*175,h);ctx.fill();ctx.fillStyle='#657652';for(let y=140;y<h;y+=155){const x=240+side*(70+(y-90)*.29);ctx.fillRect(x-12,y-45,24,88);ctx.beginPath();ctx.arc(x,y-50,27,0,7);ctx.fill()}}
  game.objects.forEach(o=>{const depth=Math.max(0,(o.y-40)/740),x=roadX(o.lane,o.y),scale=.28+depth*.95;if(o.type==='coin'){ctx.fillStyle='#6b4b21';ctx.beginPath();ctx.ellipse(x+3,o.y+5,13*scale,5*scale,0,0,7);ctx.fill();ctx.fillStyle='#ffd25e';ctx.beginPath();ctx.arc(x,o.y,17*scale,0,7);ctx.fill();ctx.strokeStyle='#fff0a2';ctx.lineWidth=2*scale;ctx.stroke();ctx.fillStyle='#a96d24';ctx.font=`${16*scale}px sans-serif`;ctx.fillText('◈',x-7*scale,o.y+5*scale)}else{ctx.fillStyle='#4c5148';ctx.beginPath();ctx.moveTo(x,o.y-27*scale);ctx.lineTo(x+25*scale,o.y+22*scale);ctx.lineTo(x-25*scale,o.y+22*scale);ctx.closePath();ctx.fill();ctx.strokeStyle='#9c9a77';ctx.lineWidth=2*scale;ctx.stroke()}});
  const px=roadX(game.lane,710),run=Math.sin(phase*2.4),bob=Math.abs(run)*6,py=685+bob;
  ctx.fillStyle='#0c2829aa';ctx.beginPath();ctx.ellipse(px,755,41,10,0,0,7);ctx.fill();
  // Runner viewed from behind: alternating limbs and body bob create a clear forward-running cadence.
  ctx.strokeStyle='#202838';ctx.lineWidth=13;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(px-9,py+49);ctx.lineTo(px-18-run*19,py+82);ctx.moveTo(px+9,py+49);ctx.lineTo(px+18+run*19,py+82);ctx.stroke();
  ctx.strokeStyle='#e2a15e';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(px-18,py+15);ctx.lineTo(px-37+run*18,py+40);ctx.moveTo(px+18,py+15);ctx.lineTo(px+37-run*18,py+40);ctx.stroke();
  ctx.fillStyle='#c64836';ctx.beginPath();ctx.moveTo(px-23,py+2);ctx.lineTo(px+23,py+2);ctx.lineTo(px+17,py+57);ctx.lineTo(px-17,py+57);ctx.closePath();ctx.fill();ctx.fillStyle='#f1b06c';ctx.beginPath();ctx.arc(px,py-15,18,0,7);ctx.fill();ctx.fillStyle='#392c28';ctx.beginPath();ctx.arc(px,py-21,19,Math.PI,0);ctx.lineTo(px+17,py-12);ctx.lineTo(px-17,py-12);ctx.fill();
  if(game.shield){ctx.strokeStyle='#9cffdc';ctx.lineWidth=4;ctx.beginPath();ctx.arc(px,py+20,58,0,7);ctx.stroke()}if(game.magnetUntil>now){ctx.strokeStyle='#f7ca63';ctx.lineWidth=3;ctx.beginPath();ctx.arc(px,py+20,70+Math.sin(phase*4)*6,0,7);ctx.stroke()}
  ctx.fillStyle='#fff';ctx.font='12px sans-serif';ctx.fillText('速度 '+speed.toFixed(1)+'/ 9.0',18,95);
}
function end(){game.over=true;cancelAnimationFrame(raf);data.coins+=game.coins;data.best=Math.max(data.best,Math.floor(game.dist));save();$('#final-distance').textContent=Math.floor(game.dist);$('#final-coins').textContent=game.coins;$('#result-overlay').classList.remove('hidden')}
updateStats();
